name: API Tests (Postman CLI)

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  run-postman-cli:
    runs-on: ubuntu-latest
    env:
      # Usa el secreto que ya creaste en GitHub Settings > Secrets and variables
      POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Postman CLI
        run: |
         curl -o- "https://dl-cli.pstmn.io/install/linux.sh" | sh


      - name: Login to Postman
        run: |
          echo "$POSTMAN_API_KEY" | postman login --with-api-key

      - name: Run collection from Postman Cloud
        run: |
          postman collection run 20016255-55c899e1-089e-4721-94ef-c6b16778af73 \
            -e 20016255-9b06f11b-cbac-45c2-9c7e-37af71a24185
