name: API Tests (Newman pulling from Postman)

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  run-newman:
    runs-on: ubuntu-latest
    env:
      POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}
      POSTMAN_COLLECTION_ID: 20016255-55c899e1-089e-4721-94ef-c6b16778af73
      POSTMAN_ENV_ID: 20016255-9b06f11b-cbac-45c2-9c7e-37af71a24185

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install jq + Newman
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          npm install -g newman newman-reporter-htmlextra

      - name: Download latest collection & environment from Postman
        run: |
          mkdir -p tests
          curl -s -H "X-Api-Key: $POSTMAN_API_KEY" \
            "https://api.getpostman.com/collections/$POSTMAN_COLLECTION_ID" \
            | jq '.collection' > tests/collection.json

          curl -s -H "X-Api-Key: $POSTMAN_API_KEY" \
            "https://api.getpostman.com/environments/$POSTMAN_ENV_ID" \
            | jq '.environment' > tests/environment.json

          # Debug opcional
          jq -r '.info.name' tests/collection.json
          jq -r '.name' tests/environment.json

      - name: Run Newman (always latest from Postman)
        run: |
          mkdir -p reports
          newman run tests/collection.json \
            -e tests/environment.json \
            -r cli,htmlextra,junit \
            --reporter-htmlextra-export reports/newman-report.html \
            --reporter-junit-export reports/newman-junit.xml
      - name: Run Newman (timestamped report)
        env:
          BRANCH_NAME: ${{ github.ref_name }}
          SHORT_SHA: ${{ github.sha }}
        run: |
          mkdir -p reports
          # Hora local de Argentina (cambiá la TZ si querés otra)
          TS_HUMAN=$(TZ=America/Argentina/Buenos_Aires date +'%Y-%m-%d %H:%M:%S')
          TS_FILE=$(TZ=America/Argentina/Buenos_Aires date +'%Y-%m-%d_%H-%M-%S')
          SHORT=${SHORT_SHA:0:7}
          TITLE="API Tests – ${BRANCH_NAME} #${GITHUB_RUN_NUMBER} (${SHORT}) – ${TS_HUMAN} ART"
      
          newman run tests/collection.json \
            -e tests/environment.json \
            -r cli,htmlextra,junit \
            --reporter-htmlextra-title "$TITLE" \
            --reporter-htmlextra-export "reports/newman-report-${TS_FILE}.html" \
            --reporter-junit-export  "reports/newman-junit-${TS_FILE}.xml"

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: newman-reports
          path: reports/
