name: API Tests (Newman)

on:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/**"
      - "tests/**"
      - "README.md"
  pull_request:
    paths:
      - "tests/**"
      - ".github/workflows/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-newman:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Newman + HTML reporter
        run: |
          npm install -g newman newman-reporter-htmlextra

      # Ajustá las rutas si tus archivos están en otro lado
      - name: Run Postman collection with Newman
        run: |
          mkdir -p reports
          newman run tests/rickandmorty_collection.json \
            -e tests/rickandmorty_environment.json \
            -r cli,htmlextra,junit \
            --reporter-htmlextra-export reports/newman-report.html \
            --reporter-junit-export reports/newman-junit.xml

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: newman-report-html
          path: reports/newman-report.html

      - name: Upload JUnit report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: newman-report-junit
          path: reports/newman-junit.xml
