name: API Tests (Newman)

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:  # permite ejecutarlo a mano

jobs:
  run-newman:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Newman + HTML reporter
        run: |
          npm install -g newman newman-reporter-htmlextra

      - name: Run Postman collection
        run: |
          mkdir -p reports
          newman run tests/rickandmorty_collection.json \
            -e tests/rickandmorty_environment.json \
            -r cli,htmlextra \
            --reporter-htmlextra-export reports/newman-report.html

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: reports/newman-report.html
